server:
  port: 8888

spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lideshuai521/springcloud.git #配置git仓库地址
          searchPaths: springcloud-config #配置仓库路径
          username: lideshuai521 #访问git仓库的用户名
          password: qq544372530 #访问git仓库的用户密码
      label: master #配置仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/